"""understand-anything-core — Python port of @understand-anything/core."""

from understand_anything.types import (
    # Enums
    EdgeType,
    NodeType,
    # Pydantic models
    AnalysisMeta,
    DomainMeta,
    GraphEdge,
    GraphNode,
    KnowledgeGraph,
    KnowledgeMeta,
    Layer,
    ProjectConfig,
    ProjectMeta,
    ThemeConfig,
    TourStep,
    # Dataclasses
    CallGraphEntry,
    ClassInfo,
    DefinitionInfo,
    EndpointInfo,
    ExportInfo,
    FunctionInfo,
    ImportInfo,
    ImportResolution,
    ReferenceResolution,
    ResourceInfo,
    SectionInfo,
    ServiceInfo,
    StepInfo,
    StructuralAnalysis,
)
from understand_anything.schema import (
    COMPLEXITY_ALIASES,
    DIRECTION_ALIASES,
    EDGE_TYPE_ALIASES,
    NODE_TYPE_ALIASES,
    GraphIssue,
    ValidationResult,
    auto_fix_graph,
    normalize_graph,
    sanitize_graph,
    validate_graph,
)
from understand_anything.persistence import (
    clear_all,
    config_path,
    fingerprints_path,
    graph_path,
    load_all,
    load_config,
    load_fingerprints,
    load_graph,
    load_meta,
    meta_path,
    output_dir,
    save_config,
    save_fingerprints,
    save_graph,
    save_meta,
    touch_meta,
)
from understand_anything.ignore import (
    DEFAULT_IGNORE_PATTERNS,
    filter_files,
    generate_understandignore,
    guess_ignore_rules,
    load_ignore_spec,
    should_ignore,
)
from understand_anything.search import (
    FuzzyMatch,
    FuzzySearchOptions,
    SemanticMatch,
    cosine_similarity,
    fuzzy_search,
    fuzzy_search_nodes,
    search_by_embedding,
)

__all__ = [
    # Enums
    "NodeType",
    "EdgeType",
    # Models
    "KnowledgeMeta",
    "DomainMeta",
    "GraphNode",
    "GraphEdge",
    "Layer",
    "TourStep",
    "ProjectMeta",
    "KnowledgeGraph",
    "ThemeConfig",
    "AnalysisMeta",
    "ProjectConfig",
    # Structural dataclasses
    "FunctionInfo",
    "ClassInfo",
    "ImportInfo",
    "ExportInfo",
    "SectionInfo",
    "DefinitionInfo",
    "ServiceInfo",
    "EndpointInfo",
    "StepInfo",
    "ResourceInfo",
    "StructuralAnalysis",
    "CallGraphEntry",
    "ImportResolution",
    "ReferenceResolution",
    # Schema / validation
    "NODE_TYPE_ALIASES",
    "EDGE_TYPE_ALIASES",
    "COMPLEXITY_ALIASES",
    "DIRECTION_ALIASES",
    "GraphIssue",
    "ValidationResult",
    "sanitize_graph",
    "normalize_graph",
    "auto_fix_graph",
    "validate_graph",
    # Persistence
    "clear_all",
    "config_path",
    "fingerprints_path",
    "graph_path",
    "load_all",
    "load_config",
    "load_fingerprints",
    "load_graph",
    "load_meta",
    "meta_path",
    "output_dir",
    "save_config",
    "save_fingerprints",
    "save_graph",
    "save_meta",
    "touch_meta",
    # Ignore
    "DEFAULT_IGNORE_PATTERNS",
    "filter_files",
    "generate_understandignore",
    "guess_ignore_rules",
    "load_ignore_spec",
    "should_ignore",
    # Search — fuzzy
    "FuzzyMatch",
    "FuzzySearchOptions",
    "fuzzy_search",
    "fuzzy_search_nodes",
    # Search — semantic
    "SemanticMatch",
    "cosine_similarity",
    "search_by_embedding",
]
