"""understand-anything-core — Python port of @understand-anything/core."""

from understand_anything.types import (
    # Enums
    EdgeType,
    NodeType,
    # Pydantic models
    AnalysisMeta,
    DomainMeta,
    GraphEdge,
    GraphNode,
    KnowledgeGraph,
    KnowledgeMeta,
    Layer,
    ProjectConfig,
    ProjectMeta,
    ThemeConfig,
    TourStep,
    # Dataclasses
    CallGraphEntry,
    ClassInfo,
    DefinitionInfo,
    EndpointInfo,
    ExportInfo,
    FunctionInfo,
    ImportInfo,
    ImportResolution,
    ReferenceResolution,
    ResourceInfo,
    SectionInfo,
    ServiceInfo,
    StepInfo,
    StructuralAnalysis,
)
from understand_anything.schema import (
    COMPLEXITY_ALIASES,
    DIRECTION_ALIASES,
    EDGE_TYPE_ALIASES,
    NODE_TYPE_ALIASES,
    GraphIssue,
    ValidationResult,
    auto_fix_graph,
    normalize_graph,
    sanitize_graph,
    validate_graph,
)

__all__ = [
    # Enums
    "NodeType",
    "EdgeType",
    # Models
    "KnowledgeMeta",
    "DomainMeta",
    "GraphNode",
    "GraphEdge",
    "Layer",
    "TourStep",
    "ProjectMeta",
    "KnowledgeGraph",
    "ThemeConfig",
    "AnalysisMeta",
    "ProjectConfig",
    # Structural dataclasses
    "FunctionInfo",
    "ClassInfo",
    "ImportInfo",
    "ExportInfo",
    "SectionInfo",
    "DefinitionInfo",
    "ServiceInfo",
    "EndpointInfo",
    "StepInfo",
    "ResourceInfo",
    "StructuralAnalysis",
    "CallGraphEntry",
    "ImportResolution",
    "ReferenceResolution",
    # Schema / validation
    "NODE_TYPE_ALIASES",
    "EDGE_TYPE_ALIASES",
    "COMPLEXITY_ALIASES",
    "DIRECTION_ALIASES",
    "GraphIssue",
    "ValidationResult",
    "sanitize_graph",
    "normalize_graph",
    "auto_fix_graph",
    "validate_graph",
]
