"""各语言内置/标准库过滤 — 避免将内置函数当作未解析引用.

每种语言提供一个已知内置符号集合, 用于在引用解析时快速过滤.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Python 内置符号
# ---------------------------------------------------------------------------

PYTHON_BUILTINS: set[str] = {
    # 内置函数 (builtins)
    "abs",
    "all",
    "any",
    "ascii",
    "bin",
    "bool",
    "breakpoint",
    "bytearray",
    "bytes",
    "callable",
    "chr",
    "classmethod",
    "compile",
    "complex",
    "copyright",
    "credits",
    "delattr",
    "dict",
    "dir",
    "divmod",
    "enumerate",
    "eval",
    "exec",
    "exit",
    "filter",
    "float",
    "format",
    "frozenset",
    "getattr",
    "globals",
    "hasattr",
    "hash",
    "help",
    "hex",
    "id",
    "input",
    "int",
    "isinstance",
    "issubclass",
    "iter",
    "len",
    "license",
    "list",
    "locals",
    "map",
    "max",
    "memoryview",
    "min",
    "next",
    "object",
    "oct",
    "open",
    "ord",
    "pow",
    "print",
    "property",
    "quit",
    "range",
    "repr",
    "reversed",
    "round",
    "set",
    "setattr",
    "slice",
    "sorted",
    "staticmethod",
    "str",
    "sum",
    "super",
    "tuple",
    "type",
    "vars",
    "zip",
    "__import__",
    # 常见标准库模块前缀
    "os",
    "sys",
    "math",
    "json",
    "re",
    "datetime",
    "collections",
    "itertools",
    "functools",
    "pathlib",
    "typing",
    "logging",
    "unittest",
    "subprocess",
    "threading",
    "asyncio",
    "io",
    "csv",
    "hashlib",
    "random",
    "statistics",
    "uuid",
    "argparse",
    "tempfile",
    "shutil",
    "abc",
    "dataclasses",
    "enum",
    "types",
    "warnings",
    "traceback",
    "textwrap",
    "string",
    "struct",
    "pickle",
    "copy",
    "pprint",
    "time",
    "base64",
    "html",
    "http",
    "urllib",
    "xml",
    "socket",
    "email",
    "sqlite3",
    "contextlib",
    "inspect",
    # 常见第三方库前缀
    "pandas",
    "numpy",
    "requests",
    "flask",
    "django",
    "sqlalchemy",
    "pytest",
    "click",
    "pydantic",
    "fastapi",
    "starlette",
    "celery",
    "redis",
    "yaml",
    "toml",
    "rich",
}


# ---------------------------------------------------------------------------
# TypeScript/JavaScript 内置符号
# ---------------------------------------------------------------------------

TYPESCRIPT_BUILTINS: set[str] = {
    # 全局对象
    "console",
    "window",
    "document",
    "globalThis",
    "process",
    "Buffer",
    "__dirname",
    "__filename",
    "module",
    "exports",
    "require",
    "setTimeout",
    "setInterval",
    "clearTimeout",
    "clearInterval",
    "setImmediate",
    "clearImmediate",
    "queueMicrotask",
    "fetch",
    "Request",
    "Response",
    "Headers",
    "AbortController",
    "AbortSignal",
    "URL",
    "URLSearchParams",
    "FormData",
    "Blob",
    "File",
    "TextEncoder",
    "TextDecoder",
    "atob",
    "btoa",
    "structuredClone",
    "performance",
    "crypto",
    "JSON",
    "Math",
    "Date",
    "RegExp",
    "Error",
    "TypeError",
    "RangeError",
    "SyntaxError",
    "ReferenceError",
    "Promise",
    "Map",
    "Set",
    "WeakMap",
    "WeakSet",
    "Array",
    "Object",
    "String",
    "Number",
    "Boolean",
    "Symbol",
    "BigInt",
    "Intl",
    "Reflect",
    "Proxy",
    "Int8Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "Int16Array",
    "Uint16Array",
    "Int32Array",
    "Uint32Array",
    "Float32Array",
    "Float64Array",
    "BigInt64Array",
    "BigUint64Array",
    "ArrayBuffer",
    "SharedArrayBuffer",
    "DataView",
    "Atomics",
    # 常见 Node.js 内置模块
    "fs",
    "path",
    "os",
    "http",
    "https",
    "net",
    "stream",
    "events",
    "util",
    "url",
    "querystring",
    "assert",
    "child_process",
    "cluster",
    "dns",
    "domain",
    "punycode",
    "readline",
    "tls",
    "zlib",
}


# ---------------------------------------------------------------------------
# C/C++ 内置符号
# ---------------------------------------------------------------------------

CPP_BUILTINS: set[str] = {
    # 标准库头文件
    "iostream",
    "fstream",
    "sstream",
    "string",
    "vector",
    "list",
    "deque",
    "queue",
    "stack",
    "set",
    "map",
    "unordered_set",
    "unordered_map",
    "algorithm",
    "iterator",
    "memory",
    "functional",
    "utility",
    "tuple",
    "thread",
    "mutex",
    "condition_variable",
    "chrono",
    "regex",
    "random",
    "cmath",
    "cstdlib",
    "cstdio",
    "cstring",
    "ctime",
    "cassert",
    "ccomplex",
    "stdio.h",
    "stdlib.h",
    "string.h",
    "math.h",
    "time.h",
    "assert.h",
    "stddef.h",
    "stdint.h",
    "stdbool.h",
    # C 标准库函数
    "printf",
    "scanf",
    "malloc",
    "free",
    "calloc",
    "realloc",
    "memcpy",
    "memset",
    "memmove",
    "strlen",
    "strcpy",
    "strcat",
    "strcmp",
    "sprintf",
    "fopen",
    "fclose",
    "fread",
    "fwrite",
    "fprintf",
    "exit",
    "abort",
    "qsort",
    "bsearch",
    "sizeof",
    "NULL",
}


# ---------------------------------------------------------------------------
# Java 内置符号
# ---------------------------------------------------------------------------

JAVA_BUILTINS: set[str] = {
    # java.lang 自动导入
    "String",
    "Object",
    "System",
    "Thread",
    "Runnable",
    "Math",
    "Integer",
    "Long",
    "Double",
    "Float",
    "Boolean",
    "Byte",
    "Short",
    "Character",
    "Class",
    "Enum",
    "Exception",
    "RuntimeException",
    "Error",
    "Throwable",
    "Override",
    "Deprecated",
    "SuppressWarnings",
    "FunctionalInterface",
    "StringBuilder",
    "StringBuffer",
    "Iterable",
    "Comparable",
    "Cloneable",
    "AutoCloseable",
    "Appendable",
    "CharSequence",
    "Readable",
    "Number",
    "Void",
    "Process",
    "Runtime",
    "StackTraceElement",
    # 常见 java.util 前缀
    "List",
    "Map",
    "Set",
    "Collection",
    "ArrayList",
    "HashMap",
    "HashSet",
    "LinkedList",
    "TreeMap",
    "TreeSet",
    "Optional",
    "Stream",
    "Arrays",
    "Collections",
    "Objects",
    "Comparator",
    "Iterator",
    "UUID",
    "Date",
    "Calendar",
    "Random",
    # 常见 java.io 前缀
    "File",
    "InputStream",
    "OutputStream",
    "Reader",
    "Writer",
    "BufferedReader",
    "BufferedWriter",
    "IOException",
    "FileNotFoundException",
}


# ---------------------------------------------------------------------------
# 按语言 ID 查询
# ---------------------------------------------------------------------------

_BUILTINS_BY_LANG: dict[str, set[str]] = {
    "python": PYTHON_BUILTINS,
    "typescript": TYPESCRIPT_BUILTINS,
    "tsx": TYPESCRIPT_BUILTINS,
    "javascript": TYPESCRIPT_BUILTINS,
    "cpp": CPP_BUILTINS,
    "c": CPP_BUILTINS,
    "java": JAVA_BUILTINS,
}


def is_builtin(symbol: str, language_id: str | None = None) -> bool:
    """检查 *symbol* 是否为对应语言的内置/标准库符号.

    Args:
        symbol: 要检查的符号名.
        language_id: 语言 ID (e.g. ``"python"``, ``"typescript"``).
            ``None`` 时只检查通用关键字.

    Returns:
        ``True`` 如果符号为内置或标准库.
    """
    if language_id and language_id in _BUILTINS_BY_LANG:
        return symbol in _BUILTINS_BY_LANG[language_id]
    # 跨语言检查
    return any(
        symbol in builtins_set
        for builtins_set in _BUILTINS_BY_LANG.values()
    )
