""".understandignore file generator.

Python port of ignore-generator.ts.  Produces a sensible set of ignore
patterns based on the project's detected languages, frameworks, and file
statistics.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# Language-specific patterns
# ---------------------------------------------------------------------------

_LANG_PATTERNS: dict[str, list[str]] = {
    "python": [
        "__pycache__",
        "*.pyc",
        "*.pyo",
        ".venv",
        "venv",
        ".tox",
        "*.egg-info",
        ".eggs",
        "dist",
        "build",
        "*.whl",
    ],
    "javascript": [
        "node_modules",
        "dist",
        "build",
        ".next",
        ".nuxt",
        "coverage",
    ],
    "typescript": [
        "node_modules",
        "dist",
        "build",
        ".next",
        ".nuxt",
        "*.tsbuildinfo",
        "coverage",
    ],
    "go": [
        "vendor",
        "*.exe",
        "*.test",
        "*.out",
    ],
    "rust": [
        "target",
        "**/*.rs.bk",
    ],
    "java": [
        "target",
        "*.class",
        "*.jar",
        "*.war",
        ".gradle",
        "build",
    ],
    "ruby": [
        ".bundle",
        "vendor/bundle",
        "*.gem",
        "tmp",
        "log",
    ],
    "php": [
        "vendor",
        "*.phar",
    ],
    "csharp": [
        "bin",
        "obj",
        "*.user",
        "*.suo",
        "packages",
    ],
    "cpp": [
        "build",
        "cmake-build-*",
        "*.o",
        "*.obj",
        "*.a",
        "*.so",
        "*.dylib",
    ],
}

_FRAMEWORK_PATTERNS: dict[str, list[str]] = {
    "django": ["staticfiles", "media", "*.sqlite3"],
    "nextjs": [".next", ".vercel"],
    "react": ["build"],
    "rails": ["tmp", "log", "public/assets", "public/packs"],
    "spring": [".mvn", "target"],
}


def _format_header(project_name: str | None = None) -> str:
    """Build the comment header block for .understandignore."""
    header = "# .understandignore — auto-generated by understand-anything-core\n"
    header += "#\n"
    header += "# This file extends .gitignore for the purpose of knowledge graph\n"
    header += "# analysis.  Files matched here will be skipped during scanning;\n"
    header += "# they still remain tracked by git (unless also in .gitignore).\n"
    header += "#\n"
    header += "# Add your own patterns below.  Use '!' prefix to un-ignore.\n"
    if project_name:
        header += f"# Project: {project_name}\n"
    header += "\n"
    return header


def guess_ignore_rules(
    *,
    languages: list[str] | None = None,
    frameworks: list[str] | None = None,
    large_files: list[str] | None = None,
) -> list[str]:
    """Produce a deduplicated, sorted list of ignore patterns.

    Patterns are collected from three sources:

    * Language-specific build/cache directories
    * Framework-specific output directories
    * Explicitly listed *large_files* (passed through as-is)
    """
    seen: set[str] = set()
    result: list[str] = []

    def _add(pattern: str) -> None:
        if pattern not in seen:
            seen.add(pattern)
            result.append(pattern)

    for lang in (languages or []):
        for pat in _LANG_PATTERNS.get(lang.lower(), []):
            _add(pat)

    for fw in (frameworks or []):
        for pat in _FRAMEWORK_PATTERNS.get(fw.lower(), []):
            _add(pat)

    for lf in (large_files or []):
        _add(lf)

    result.sort()
    return result


def generate_understandignore(
    project_root: Path,
    *,
    project_name: str | None = None,
    languages: list[str] | None = None,
    frameworks: list[str] | None = None,
    large_files: list[str] | None = None,
    overwrite: bool = False,
) -> Path:
    """Write a ``.understandignore`` file to *project_root*.

    Parameters
    ----------
    project_root:
        The root directory of the project.
    project_name:
        Display name used in the comment header.
    languages:
        Detected programming languages (e.g. ``["python", "typescript"]``).
    frameworks:
        Detected frameworks (e.g. ``["django", "react"]``).
    large_files:
        Individual file paths that should be ignored (e.g. large generated
        JSON fixtures).
    overwrite:
        If ``False`` (default) and the file already exists, the call is a
        no-op.  If ``True``, the existing file is replaced.

    Returns the path to the file (whether or not it was written).
    """
    target = project_root / ".understandignore"

    if target.exists() and not overwrite:
        return target

    header = _format_header(project_name)
    rules = guess_ignore_rules(
        languages=languages, frameworks=frameworks, large_files=large_files
    )

    body = "\n".join(rules) + "\n" if rules else ""
    target.write_text(header + body)
    return target
