""".understandignore 文件生成器。

提供两种生成模式：

1. **主动生效模式** — :func:`generate_understandignore` 根据传入的语言/框架参数
   生成直接生效的 ``.understandignore`` 文件（Python 便利 API）。

2. **Starter 建议模式** — :func:`generate_starter_ignore_file` 扫描项目目录和
   ``.gitignore``，生成注释形式的建议文件（对标 TypeScript
   ``generateStarterIgnoreFile`` 的等价实现），由用户手动取消注释来启用。
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

# ---------------------------------------------------------------------------
# Language-specific patterns
# ---------------------------------------------------------------------------

_LANG_PATTERNS: dict[str, list[str]] = {
    "python": [
        "__pycache__",
        "*.pyc",
        "*.pyo",
        ".venv",
        "venv",
        ".tox",
        "*.egg-info",
        ".eggs",
        "dist",
        "build",
        "*.whl",
    ],
    "javascript": [
        "node_modules",
        "dist",
        "build",
        ".next",
        ".nuxt",
        "coverage",
    ],
    "typescript": [
        "node_modules",
        "dist",
        "build",
        ".next",
        ".nuxt",
        "*.tsbuildinfo",
        "coverage",
    ],
    "go": [
        "vendor",
        "*.exe",
        "*.test",
        "*.out",
    ],
    "rust": [
        "target",
        "**/*.rs.bk",
    ],
    "java": [
        "target",
        "*.class",
        "*.jar",
        "*.war",
        ".gradle",
        "build",
    ],
    "ruby": [
        ".bundle",
        "vendor/bundle",
        "*.gem",
        "tmp",
        "log",
    ],
    "php": [
        "vendor",
        "*.phar",
    ],
    "csharp": [
        "bin",
        "obj",
        "*.user",
        "*.suo",
        "packages",
    ],
    "cpp": [
        "build",
        "cmake-build-*",
        "*.o",
        "*.obj",
        "*.a",
        "*.so",
        "*.dylib",
    ],
}

_FRAMEWORK_PATTERNS: dict[str, list[str]] = {
    "django": ["staticfiles", "media", "*.sqlite3"],
    "nextjs": [".next", ".vercel"],
    "react": ["build"],
    "rails": ["tmp", "log", "public/assets", "public/packs"],
    "spring": [".mvn", "target"],
}

# ---------------------------------------------------------------------------
# Starter generator — TS-equivalent constants
# ---------------------------------------------------------------------------

_DETECTABLE_DIRS: list[tuple[str, str]] = [
    ("__tests__", "__tests__/"),
    ("test", "test/"),
    ("tests", "tests/"),
    ("fixtures", "fixtures/"),
    ("testdata", "testdata/"),
    ("docs", "docs/"),
    ("examples", "examples/"),
    ("scripts", "scripts/"),
    ("migrations", "migrations/"),
    (".storybook", ".storybook/"),
]

_GENERIC_SUGGESTIONS: list[str] = [
    "*.test.*",
    "*.spec.*",
    "*.snap",
]


def _is_covered_by_defaults(pattern: str, defaults: list[str]) -> bool:
    """检查一条 ignore 规则是否已被默认规则覆盖。

    比较时去除尾部斜杠，使 ``dist/`` 等价于 ``dist``、``coverage`` 等价于
    ``coverage/``。

    Args:
        pattern: 待检查的 ignore 规则。
        defaults: 默认规则列表（如 :data:`DEFAULT_IGNORE_PATTERNS`）。

    Returns:
        如果 *pattern* 已被默认规则覆盖则返回 ``True``。
    """
    def _normalize(p: str) -> str:
        return p.rstrip("/")

    normalized = _normalize(pattern)
    return any(_normalize(d) == normalized for d in defaults)


def _format_header(project_name: str | None = None) -> str:
    """生成 .understandignore 的注释头部。

    Args:
        project_name: 可选的项目名称，会写入注释中。

    Returns:
        格式化的注释头部字符串。
    """
    header = "# .understandignore — auto-generated by understand-anything-core\n"
    header += "#\n"
    header += "# This file extends .gitignore for the purpose of knowledge graph\n"
    header += "# analysis.  Files matched here will be skipped during scanning;\n"
    header += "# they still remain tracked by git (unless also in .gitignore).\n"
    header += "#\n"
    header += "# Add your own patterns below.  Use '!' prefix to un-ignore.\n"
    if project_name:
        header += f"# Project: {project_name}\n"
    header += "\n"
    return header


def _format_starter_header(project_name: str | None = None) -> str:
    """生成 starter 版 .understandignore 注释头部，对标 TS HEADER。

    Args:
        project_name: 可选的项目名称，会写入注释中。

    Returns:
        starter 格式的注释头部字符串。
    """
    header = "# .understandignore — patterns for files/dirs to exclude from analysis\n"
    header += "# Syntax: same as .gitignore (globs, # comments, ! negation,"
    header += " trailing / for dirs)\n"
    header += "# Lines below are suggestions — uncomment to activate.\n"
    header += "# Use ! prefix to force-include something excluded by defaults.\n"
    header += "#\n"
    header += "# Built-in defaults (always excluded unless negated):\n"
    header += "#   node_modules/, .git/, dist/, build/, obj/, *.lock, *.min.js,"
    header += " etc.\n"
    header += "#\n"
    if project_name:
        header += f"# Project: {project_name}\n"
    return header


def guess_ignore_rules(
    *,
    languages: list[str] | None = None,
    frameworks: list[str] | None = None,
    large_files: list[str] | None = None,
) -> list[str]:
    """生成去重、排序后的 ignore 规则列表。

    规则来源有三个：

    * 语言特定的 build/cache 目录
    * 框架特定的输出目录
    * 显式传入的 *large_files*（原样追加）

    Args:
        languages: 检测到的编程语言列表（如 ``["python", "typescript"]``）。
        frameworks: 检测到的框架列表（如 ``["django", "react"]``）。
        large_files: 需要忽略的单个文件路径（如大型生成的 JSON 文件）。

    Returns:
        去重并排序后的 ignore 规则列表。
    """
    seen: set[str] = set()
    result: list[str] = []

    def _add(pattern: str) -> None:
        if pattern not in seen:
            seen.add(pattern)
            result.append(pattern)

    for lang in (languages or []):
        for pat in _LANG_PATTERNS.get(lang.lower(), []):
            _add(pat)

    for fw in (frameworks or []):
        for pat in _FRAMEWORK_PATTERNS.get(fw.lower(), []):
            _add(pat)

    for lf in (large_files or []):
        _add(lf)

    result.sort()
    return result


def generate_understandignore(
    project_root: Path,
    *,
    project_name: str | None = None,
    languages: list[str] | None = None,
    frameworks: list[str] | None = None,
    large_files: list[str] | None = None,
    overwrite: bool = False,
) -> Path:
    """将 ``.understandignore`` 文件写入 *project_root*。

    生成的是**主动生效**的 ignore 规则文件，基于传入的语言/框架/大文件参数。

    Args:
        project_root: 项目根目录。
        project_name: 用于注释头部的显示名称。
        languages: 检测到的编程语言（如 ``["python", "typescript"]``）。
        frameworks: 检测到的框架（如 ``["django", "react"]``）。
        large_files: 需要忽略的单个文件路径（如大型生成的 JSON 文件）。
        overwrite: 若为 ``False``（默认）且文件已存在，则不做任何操作。
            若为 ``True``，则覆盖已有文件。

    Returns:
        文件路径（无论是否实际写入）。
    """
    target = project_root / ".understandignore"

    if target.exists() and not overwrite:
        return target

    header = _format_header(project_name)
    rules = guess_ignore_rules(
        languages=languages, frameworks=frameworks, large_files=large_files
    )

    body = "\n".join(rules) + "\n" if rules else ""
    target.write_text(header + body)
    return target


def generate_starter_ignore_file(
    project_root: Path,
    *,
    project_name: str | None = None,
) -> str:
    """生成 starter 建议版 ``.understandignore`` 文件内容（对标 TS generateStarterIgnoreFile）。

    与 :func:`generate_understandignore` 不同，此函数生成的规则以注释形式写出，
    供用户手动取消注释来启用。三段式结构：

    1. ``.gitignore`` 中不在默认规则里的规则 → 注释建议
    2. 项目下存在的可检测目录（如 ``tests/``、``docs/`` 等）→ 注释建议
    3. 通用测试文件模式（``*.test.*``、``*.spec.*``、``*.snap``）→ 总是生成

    此函数**不写文件**，只返回字符串内容，由调用方决定是否写入。

    Args:
        project_root: 项目根目录。
        project_name: 可选的项目名称，写入注释头部。

    Returns:
        starter 版的 ``.understandignore`` 文件内容字符串。
    """
    # 延迟导入以避免循环依赖
    from understand_anything.ignore.filter import DEFAULT_IGNORE_PATTERNS

    sections: list[str] = []

    # 1. Header（对标 TS HEADER）
    sections.append(_format_starter_header(project_name))

    # 2. Section 1 — .gitignore 中不在默认规则里的规则
    gitignore_path = project_root / ".gitignore"
    gitignore_rules: list[str] = []
    if gitignore_path.is_file():
        for raw in gitignore_path.read_text().splitlines():
            line = raw.strip()
            if line and not line.startswith("#"):
                gitignore_rules.append(line)

    non_default_gitignore = [
        r for r in gitignore_rules
        if not _is_covered_by_defaults(r, DEFAULT_IGNORE_PATTERNS)
    ]
    if non_default_gitignore:
        sections.append(
            "# --- From .gitignore (uncomment to exclude) ---\n"
        )
        sections.extend(f"# {rule}" for rule in non_default_gitignore)
        sections.append("")

    # 3. Section 2 — 检测到的目录（对标 TS DETECTABLE_DIRS）
    detected: list[str] = []
    for dir_name, pattern in _DETECTABLE_DIRS:
        if (project_root / dir_name).is_dir():
            detected.append(pattern)

    if detected:
        sections.append(
            "# --- Detected directories (uncomment to exclude) ---\n"
        )
        sections.extend(f"# {pattern}" for pattern in detected)
        sections.append("")

    # 4. Section 3 — 通用测试文件模式（对标 TS GENERIC_SUGGESTIONS，总是生成）
    sections.append(
        "# --- Test file patterns (uncomment to exclude) ---\n"
    )
    sections.extend(f"# {pattern}" for pattern in _GENERIC_SUGGESTIONS)
    sections.append("")

    return "\n".join(sections)
